### PR TITLE
Bugfixes - IPC

### PR DESCRIPTION
**Pull request by jack-fractal**
I thought I'd open a pull request with fixes for any issues that pop up regarding the IPC stuff. So far there's just this one.

### CODE REVIEW

**Comment by Zuhayr** [comment]
May want to look into porting the IPC rewrite from Bay.

**Comment by jack-fractal** [comment]
What's in that one? We just did a big cosmetic revamp for them. I didn't touch their mechanics.

**Comment by SoundScopes** [comment]
Last time this was discussed we weren't going to follow with Bay's IPC code.

**Comment by Zuhayr** [comment]
Bay IPC rewrite just generalized the snowflake IPC functionality to all prosthetic limbs and cleaned up the existence of IS_SYNTHETIC. No real reason to avoid it but your call.

**Pull request merged**
