### PR TITLE
Paradise NanoUI Door Control

### PR DESCRIPTION
**Pull request by jack-fractal**
This is described here:

http://aurorastation.org/forums/viewtopic.php?f=18&t=2192

It's modifies the door control UI, both of them. The wire controls are extracted into a datum/wires abstraction that should make hackables easier to work with.

### CODE REVIEW

**Comment by SoundScopes** [comment]
Looks nice, will be adding to the next update

**Comment by jack-fractal** [comment]
Weird, ok. I didn't see this. I'll take a look.

**Comment by jack-fractal** [comment]
I _think_ this fixed it. Crossing my fingers because I don't think I ever saw it before either.

**Comment by SoundScopes** [comment]
Just so you don't panic on why I labeled your PR as invalid.
Since we had a massive code/map/icon update, I found it easier to take a copy of your fork and merge all 3 forks together manually.

**Comment by jack-fractal** [comment]
Ah, ok! Makes sense. Thanks for telling me.

**Comment by SoundScopes** [comment]
No problem and thank you for putting the time to port this.

**Comment by mwerezak** [comment]
Actually you can thank @PsiOmegaDelta for developing the wires datum system/

**Comment by PsiOmegaDelta** [comment]
I just ported the wire datums from /tg/.

**Pull request closed without merging**
