### PR TITLE
Porting UI changes for AI's and Robots

### PR DESCRIPTION
**Pull request by jack-fractal**
Gives AI's a set of icons for their more common tasks.
Makes Cyborg inventories work like backpacks.

PS: If map modifications aren't done on github, where _are_ they done?

### CODE REVIEW

**Comment by SoundScopes** [comment]
They are done over a dropbox and only one person uploads a new map at a time.
This removes the problems that we have had where changes are lost or major conflicts are caused.
At the time of your map update commit, there was already a version of the map with the fix you made on my computer.

**Comment by Zuhayr** [comment]
Why not just use the mapmerge driver?

**Comment by SoundScopes** [comment]
Because of problems we have run into in the past with other people not knowing how to use it properly.

**Comment by jack-fractal** [comment]
Ah, that makes sense. Cool beans. 

Do you need anything more from me for this change?

**Comment by SoundScopes** [comment]
On the borgs if you put a module away while the inventory is open the contents on the hud doesn't update until you open/close it or take something else out.
All borgs have access to Med and Sec huds?

**Comment by jack-fractal** [comment]
Yes. All borgs have access to sec and/or medical huds. So do AI's. I have a plan on how to make this more interesting in the future, but for right now this works fine.

**Comment by SoundScopes** [comment]
Please inform me of the plan as right now I disagree with all borgs getting access to them. There are assigned modules for a reason and it voids some of them.

**Comment by jack-fractal** [comment]
Well ok. It doesn't really void anything exactly, but I should remove the sec and med huds from the modules as they're no longer used. 

All it does is give the other cyborgs access to that info, as well as AI's. 

They already have access to all that information anyway, on the various computers. This just makes it easier to acquire.

**Comment by SoundScopes** [comment]
No, removing the huds from the modules is not what was being asked.
Anyone can get access to the information in any department, doesn't mean they should have it from the start.
This includes borgs, the modules are assigned by department and should only have easy access to them if they are working there. We do not want engi, mining, service, or other borgs acting as security or medical.

**Comment by jack-fractal** [comment]
Hmm... well I haven't seen people doing that on the other servers where this change is live. Do you think that the people on Aurora are specifically prone to that kind of behavior? If so, I'm sure I can work something out.

**Comment by SoundScopes** [comment]
This is Aurora, not other servers and we don't want to be like every other server out there.
The AI is fine but having it for the borgs is not wanted at the moment.
Revert the change please.

**Comment by jack-fractal** [comment]
I'm not really interested in arguing this. I have a change half way finished that will just add the huds to the relevant modules. Will that be all right?

**Comment by jack-fractal** [comment]
Hokay! All done.

**Comment by jack-fractal** [comment]
Hokay NOW I'm done.

**Comment by jack-fractal** [comment]
I'm not sure how things really get merged on this server. You mentioned last time that you weren't merging it yet, but that was three days ago. 

Is there anything else you need from me before merging this?

**Comment by skull132** [comment]
Hi, Head Dev here, just got back. We'll be looking at this over the weekend, along with some other fixes and things.

**Comment by jack-fractal** [comment]
Thanks for the update! That's good to know.

**Pull request merged**
